### ISSUE TITLE
Packagist not showing the latest released version

### ISSUE THREAD

**Issue by benjaminhirsch** [contentful/contentful-laravel#19]
Packagist is still showing 2.0.0 as the latest released version instead of 3.0.0 Maybe the hook isn't working anymore?

https://packagist.org/packages/contentful/laravel

**Comment by dborsatto** [comment]
Packagist hooks have been failing more than usual, recently. I'll trigger a manual update ☺️

**Comment by dborsatto** [comment]
It's now updated, it might take a few minutes to purge packagist cache 👍
