### ISSUE TITLE
Requested package contentful/laravel @beta is satisfiable by contentful/laravel[dev-master, 0.6.x-dev] but these conflict with project requirements

### ISSUE THREAD

**Issue by heruputra** [contentful/contentful-laravel#2]
Hi,

I got "- The requested package contentful/laravel @beta is satisfiable by contentful/laravel[dev-master, 0.6.x-dev] but these conflict with your requirements or minimum-stability." when installing this package with "composer require contentful/laravel:@beta" command in Laravel 5.3 fresh installation.

**Comment by pmatseykanets** [comment]
@heruputra If you haven't figured this out yet you need to run

```
composer require contentful/laravel:@dev
```

Male sure that you have in your composer.json
```
{
    ...
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

**Comment by realityking** [comment]
I just tagged a beta so this should now work. Sorry for the long delay.
