### ISSUE TITLE
Preview feature is not working

### ISSUE THREAD

**Issue by zmiKaminski** [contentful/contentful-laravel#26]
This line of code:

https://github.com/contentful/contentful-laravel/blob/4.0.0/src/ContentfulServiceProvider.php#L53

Am I reading this right?  If `preview` use the `delivery` host.

**Comment by dborsatto** [comment]
Oops, you're right. I'll fix this asap!

**Comment by dborsatto** [comment]
Fixed in #27

**Comment by zmiKaminski** [comment]
Thanks for the quick fix!!
