### ISSUE TITLE
About config('contentful')

### ISSUE THREAD

**Issue by nicolaaretini** [contentful/contentful-laravel#35]
Wonder why you set in your:
contentful-laravel/src/ContentfulServiceProvider.php
to threat index parameters string with a dot notation.

This is creating confusion for standard Laravel config behaviour,
since dot is used to manage array hierarchies.

i.e.
// instead of:

`return [
   

    'delivery.space' => env('CONTENTFUL_SPACE_ID'),
...
]`

// I'd expect:
`return [
    
    'delivery' => [
                       'space' => env('CONTENTFUL_SPACE_ID')
     ],
...
]`

so I can access my configs like standard way

$env_id=config('contentful.delivery.space');

and not like 

$env_id=config('contentful')['delivery.space'];

am I missing something?
Thanks

**Comment by pgrigoruta** [comment]
Please see version 7.0.0 (major version bump), that contains the fix you suggested. Thanks for noticing!
