### ISSUE TITLE
Support for Laravel 8.x

### ISSUE THREAD

**Issue by mrbenosborne** [contentful/contentful-laravel#38]
Hi there :wave:

Do you have a timescale for supporting Laravel 8.x?

**Comment by pgrigoruta** [comment]
Hi @benjaminhirsch , we should have it ready in a few weeks.

**Comment by mrbenosborne** [comment]
Great! Thanks @pgrigoruta

**Comment by benjaminhirsch** [comment]
> Hi @benjaminhirsch , we should have it ready in a few weeks.

I guess you accidentally mentioned me here? :-)

**Comment by pgrigoruta** [comment]
Version 8.0.0 has just been published which supports Laravel 8.
