### ISSUE TITLE
Unmatched Guzzle-Version

### ISSUE THREAD

**Issue by LrMiLoef** [contentful/contentful-laravel#43]
I just tried to install the current version of contentful-laravel within my laravel application (v8.65) and i got an error:

```  
Problem 1
    - contentful/core[3.0.0, ..., 3.0.2] require guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - contentful/core[3.0.3, ..., 3.1.1] require guzzlehttp/psr7 ^1.5|^1.6 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - contentful/laravel 8.1.0 requires contentful/core ^3.0 -> satisfiable by contentful/core[3.0.0, ..., 3.1.1].
    - Root composer.json requires contentful/laravel ^8.1 -> satisfiable by contentful/laravel[8.1.0].
```

Can you update the requirements in contentful/core package ? Or is there anything else i can do to use this package?

**Comment by Sebb767** [comment]
Hi!
It seems you're manually requiring guzzlehttp 7 in your composer.json, while contentful-core is still on version 6. The quick fix is to fall back to guzzlehttp 6 in your composer.json. In the long run, we'll probably also make the jump to guzzlehttp 7, but I need to check for changes in the new version before doing so.

**Comment by daniyals** [comment]
Laravel requires Guzzle 7, and im trying to install the package on Laravel 8 vanilla install and its giving me an error, so this definitely needs an update on the package.

**Comment by Sebb767** [comment]
Hi @LrMiLoef @daniyals,

Guzzle is now upgraded in contentful-core. Could you kindly check whether this fixed the problem?
