### ISSUE TITLE
Older version of Rich Text dependency 

### ISSUE THREAD

**Issue by akrug-va529** [contentful/contentful-laravel#48]
I am running into errors with the processing rich text fields that have superscripts in them. It seems to be due to the fact that the version of contentful/rich-text required in this package is an older one that doesn't include these html tags. Is it possible to update the Composer requirements to use the more updated versions of the dependencies for this SDK.

**Comment by Sebb767** [comment]
Should be fixed with [v9.0.0](https://github.com/contentful/contentful-laravel/releases/tag/9.0.0)
