### ISSUE TITLE
Update documentation on website

### ISSUE THREAD

**Issue by beneverard** [contentful/contentful-laravel#6]
Apologies for leaving an issue in the repo, I had a hard time installing this package from the docs on the website but then realised they're different here.

I think the [website documentation](https://www.contentful.com/developers/docs/php/tutorials/getting-started-with-contentful-and-laravel/) needs updating to the readme here.

**Comment by realityking** [comment]
Sorry for missing this ticket @beneverard. Somehow it looks like we managed to get some symfony in our larval docs - I'll take care of it :)

**Comment by beneverard** [comment]
@realityking Wonderful :-)

**Comment by realityking** [comment]
This has been fixed and will go out with the next deployment of our docs. Thanks :)
