### ISSUE TITLE
Update composer.json

### ISSUE THREAD

**Issue by JesperKoldHansen** [contentful/contentful-laravel#7]
It seems that the laravel facade does not use the latest version of the contentfull api package. It uses version 1.0.0 but 1.2 is out at this current time.

Please update, since I am getting my log spammed due to s problem with the offsetGet function.

**Comment by dborsatto** [comment]
Hey @JesperKoldHansen,
we are going to release the CDA SDK version 2.0 soon (hopefully even this week). Once that is done, we'll update this package's `composer.json` to use the newest version 👍

**Comment by davidlapham** [comment]
Any update on this? Not sure if its a connected issue but the vendor publish is not creating the config file.

**Comment by realityking** [comment]
Hey,

we just release version 2.0 of the SDK, we'll update the integration later today or tomorrow.

Thanks for your patience.

**Comment by dborsatto** [comment]
Fixed in [2.0.0](https://github.com/contentful/contentful-laravel/releases/tag/2.0.0). @JesperKoldHansen let us know if you have any other problems!
